services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      auto.create.topics.enable: "true"
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  workout-integration:
    image: aznu-workout/workoutintegration:latest
    depends_on:
      - db
      - kafka
      - workout-soap-client
      - workout-rest-client
    environment:
      spring.kafka.bootstrap-servers: kafka:9092
      camel.component.kafka.brokers: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9999"
    ports:
      - "8080:8080"
      - "9999:9999"
  workout-soap-service:
    image: aznu-workout/workoutplannersoap:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
        - "8081:8081"
  workout-soap-client:
    image: aznu-workout/workoutplannersoapclient:latest
    depends_on:
      - kafka
      - workout-soap-service
    environment:
      spring.kafka.bootstrap-servers: kafka:9092
      workout.gateway.url: http://workout-soap-service:8080
    ports:
      - "8082:8082"
  workout-rest-service:
    image: aznu-workout/workoutplannerrestservice:latest
    depends_on:
      - db
    environment:
      spring.kafka.bootstrap-servers: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9998"
    ports:
        - "8083:8083"
        - "9998:9998"
  workout-rest-client:
    image: aznu-workout/workoutplannerrestclient:latest
    depends_on:
      - kafka
      - workout-rest-service
    environment:
      spring.kafka.bootstrap-servers: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      workout.gateway.url: http://workout-rest-service:8083
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9997"
    ports:
      - "8090:8090"
      - "9997:9997"
  workout-ui:
    image: aznu-workout/workoutui:latest
    depends_on:
      - workout-integration
    ports:
      - "8085:8085"
    environment:
      workout.gateway.url: http://workout-integration:8080