
package put.poznan.pl.michalxpz.workoutplannersoap;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2025-01-26T16:21:16.777+01:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "WorkoutSOAPException", targetNamespace = "http://workoutplannersoap.michalxpz.pl.poznan.put/")
public class WorkoutSOAPException_Exception extends Exception {

    private WorkoutSOAPException faultInfo;

    public WorkoutSOAPException_Exception() {
        super();
    }

    public WorkoutSOAPException_Exception(String message) {
        super(message);
    }

    public WorkoutSOAPException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WorkoutSOAPException_Exception(String message, WorkoutSOAPException workoutSOAPException) {
        super(message);
        this.faultInfo = workoutSOAPException;
    }

    public WorkoutSOAPException_Exception(String message, WorkoutSOAPException workoutSOAPException, Throwable cause) {
        super(message, cause);
        this.faultInfo = workoutSOAPException;
    }

    public WorkoutSOAPException getFaultInfo() {
        return this.faultInfo;
    }
}
