
package put.poznan.pl.michalxpz.workoutplannersoap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2025-01-26T16:21:16.740+01:00
 * Generated source version: 4.0.5
 *
 */
public final class WorkoutService_WorkoutServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://workoutplannersoap.michalxpz.pl.poznan.put/", "WorkoutServiceService");

    private WorkoutService_WorkoutServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WorkoutServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WorkoutServiceService ss = new WorkoutServiceService(wsdlURL, SERVICE_NAME);
        WorkoutService port = ss.getWorkoutServicePort();

        {
        System.out.println("Invoking deleteWorkout...");
        Long _deleteWorkout_arg0 = null;
        port.deleteWorkout(_deleteWorkout_arg0);


        }
        {
        System.out.println("Invoking getAllWorkouts...");
        java.util.List<WorkoutSOAPResponse> _getAllWorkouts__return = port.getAllWorkouts();
        System.out.println("getAllWorkouts.result=" + _getAllWorkouts__return);


        }
        {
        System.out.println("Invoking addWorkout...");
        AddWorkoutSOAPRequest _addWorkout_arg0 = null;
        try {
            WorkoutSOAPResponse _addWorkout__return = port.addWorkout(_addWorkout_arg0);
            System.out.println("addWorkout.result=" + _addWorkout__return);

        } catch (WorkoutSOAPException_Exception e) {
            System.out.println("Expected exception: WorkoutSOAPException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getWorkoutsByMuscle...");
        String _getWorkoutsByMuscle_arg0 = "";
        java.util.List<WorkoutSOAPResponse> _getWorkoutsByMuscle__return = port.getWorkoutsByMuscle(_getWorkoutsByMuscle_arg0);
        System.out.println("getWorkoutsByMuscle.result=" + _getWorkoutsByMuscle__return);


        }
        {
        System.out.println("Invoking updateWorkout...");
        UpdateWorkoutSOAPRequest _updateWorkout_arg0 = null;
        try {
            WorkoutSOAPResponse _updateWorkout__return = port.updateWorkout(_updateWorkout_arg0);
            System.out.println("updateWorkout.result=" + _updateWorkout__return);

        } catch (WorkoutSOAPException_Exception e) {
            System.out.println("Expected exception: WorkoutSOAPException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking deleteAllWorkouts...");
        port.deleteAllWorkouts();


        }
        {
        System.out.println("Invoking getWorkoutById...");
        Long _getWorkoutById_arg0 = null;
        try {
            WorkoutSOAPResponse _getWorkoutById__return = port.getWorkoutById(_getWorkoutById_arg0);
            System.out.println("getWorkoutById.result=" + _getWorkoutById__return);

        } catch (WorkoutSOAPException_Exception e) {
            System.out.println("Expected exception: WorkoutSOAPException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getWorkoutsByEquipment...");
        String _getWorkoutsByEquipment_arg0 = "";
        java.util.List<WorkoutSOAPResponse> _getWorkoutsByEquipment__return = port.getWorkoutsByEquipment(_getWorkoutsByEquipment_arg0);
        System.out.println("getWorkoutsByEquipment.result=" + _getWorkoutsByEquipment__return);


        }
        {
        System.out.println("Invoking getWorkoutsByAuthor...");
        String _getWorkoutsByAuthor_arg0 = "";
        java.util.List<WorkoutSOAPResponse> _getWorkoutsByAuthor__return = port.getWorkoutsByAuthor(_getWorkoutsByAuthor_arg0);
        System.out.println("getWorkoutsByAuthor.result=" + _getWorkoutsByAuthor__return);


        }
        {
        System.out.println("Invoking getWorkoutsByType...");
        String _getWorkoutsByType_arg0 = "";
        java.util.List<WorkoutSOAPResponse> _getWorkoutsByType__return = port.getWorkoutsByType(_getWorkoutsByType_arg0);
        System.out.println("getWorkoutsByType.result=" + _getWorkoutsByType__return);


        }
        {
        System.out.println("Invoking getWorkoutsByDifficulty...");
        String _getWorkoutsByDifficulty_arg0 = "";
        java.util.List<WorkoutSOAPResponse> _getWorkoutsByDifficulty__return = port.getWorkoutsByDifficulty(_getWorkoutsByDifficulty_arg0);
        System.out.println("getWorkoutsByDifficulty.result=" + _getWorkoutsByDifficulty__return);


        }

        System.exit(0);
    }

}
