package put.poznan.pl.michalxpz.workoutplannersoap;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2025-01-26T16:21:16.787+01:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "WorkoutServiceService",
                  wsdlLocation = "http://workout-soap-service:8081/soap-api/service/workout?wsdl",
                  targetNamespace = "http://workoutplannersoap.michalxpz.pl.poznan.put/")
public class WorkoutServiceService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://workoutplannersoap.michalxpz.pl.poznan.put/", "WorkoutServiceService");
    public static final QName WorkoutServicePort = new QName("http://workoutplannersoap.michalxpz.pl.poznan.put/", "WorkoutServicePort");
    static {
        URL url = null;
        try {
            url = URI.create("http://workout-soap-service:8081/soap-api/service/workout?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WorkoutServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://workout-soap-service:8081/soap-api/service/workout?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WorkoutServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WorkoutServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkoutServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WorkoutServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WorkoutServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WorkoutServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WorkoutService
     */
    @WebEndpoint(name = "WorkoutServicePort")
    public WorkoutService getWorkoutServicePort() {
        return super.getPort(WorkoutServicePort, WorkoutService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkoutService
     */
    @WebEndpoint(name = "WorkoutServicePort")
    public WorkoutService getWorkoutServicePort(WebServiceFeature... features) {
        return super.getPort(WorkoutServicePort, WorkoutService.class, features);
    }

}
